FROM node:20-alpine

# Cài thêm bash và git cho frontend
RUN apk update && apk add --no-cache bash git

WORKDIR /workspaces

# Tương tự backend, ngủ yên chờ ông giáo gõ lệnh npm start
CMD ["sleep", "infinity"]