name: da-project 

services:
  # 1. DATABASE
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle_db
    ports:
      - "1522:1521"
    environment:
      ORACLE_PASSWORD: oracle
      TZ: Asia/Ho_Chi_Minh 
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./sql-init:/container-entrypoint-initdb.d 
    networks:
      - nhom15-network
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 15s
      timeout: 10s
      retries: 10

  # 2. BACKEND
  backend:
    build:
      context: ../backend  # CHÚ Ý: Đã thụt lề vào trong chữ build, và để '..' để trỏ ra thư mục 'da'
      dockerfile: ../.devcontainer/backend/Dockerfile
    container_name: spring_backend
    command: sleep infinity
    ports:
      - "8080:8080"
    volumes:
      - ..:/workspaces/da
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/XE
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: oracle
      TZ: Asia/Ho_Chi_Minh 
    depends_on:
      oracle-db:
        condition: service_healthy 
    networks:
      - nhom15-network

  # 3. FRONTEND
  frontend:
    build:
      context: ../frontend  # CHÚ Ý: Đã thụt lề vào trong chữ build
      dockerfile: ../.devcontainer/frontend/Dockerfile
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - nhom15-network

networks:
  nhom15-network:
    driver: bridge

volumes:
  oracle-data: