spring.application.name=demo

# SỬA Ở ĐÂY: Kết nối dùng tên service trong docker-compose
# Cấu trúc: jdbc:oracle:thin:@<service_name>:<port>/<service_name_oracle>
spring.datasource.url=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
spring.datasource.username=admin
spring.datasource.password=oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA & Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Cấu hình Flyway
spring.flyway.enabled=true
spring.flyway.user=admin
spring.flyway.password=oracle
# Bỏ schemas nếu ông muốn nó tự nhận theo user
spring.flyway.baseline-on-migrate=true