-- ============================================================
-- FILE   : V2_Feature_PostgreSQL.sql
-- PROJECT: Hệ Thống Quản Lý Dịch Vụ Thị Lực & Thiết Bị Y Tế
-- VERSION: Bổ sung chức năng thiếu so với đặc tả
-- ============================================================

-- ============================================================
-- [G1] GIỎ HÀNG — E-COMMERCE
-- ============================================================

CREATE TABLE GIO_HANG (
    MAGH      VARCHAR(10) PRIMARY KEY,
    MAKH      VARCHAR(10) NOT NULL,
    NGAYTAO   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TRANG_THAI VARCHAR(20) DEFAULT 'Đang dùng',
    FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH)
);

CREATE TABLE CT_GIO_HANG (
    MAGH      VARCHAR(10),
    MASP      VARCHAR(10),
    SOLUONG   NUMERIC NOT NULL,
    GIA_TAI_THOI_DIEM NUMERIC(15,2),
    NGAY_THEM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MAGH, MASP),
    FOREIGN KEY (MAGH) REFERENCES GIO_HANG(MAGH),
    FOREIGN KEY (MASP) REFERENCES SAN_PHAM(MASP)
);

CREATE SEQUENCE SEQ_GIO_HANG START 1 CACHE 20;

CREATE OR REPLACE FUNCTION trg_gen_magh_func()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.MAGH IS NULL THEN
        NEW.MAGH := 'GH' || LPAD(nextval('SEQ_GIO_HANG')::text, 6, '0');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_GEN_MAGH
BEFORE INSERT ON GIO_HANG
FOR EACH ROW EXECUTE FUNCTION trg_gen_magh_func();

CREATE INDEX IDX_GH_MAKH ON GIO_HANG (MAKH);
CREATE INDEX IDX_GH_TRANG ON GIO_HANG (TRANG_THAI);


-- ============================================================
-- [G2] ĐÁNH GIÁ & RATING BÁC SĨ
-- ============================================================

CREATE TABLE DANH_GIA (
    MADG      VARCHAR(10) PRIMARY KEY,
    MAHOSO    VARCHAR(10) NOT NULL,
    MAKH      VARCHAR(10) NOT NULL,
    MANS      VARCHAR(10) NOT NULL,
    SO_SAO    INTEGER NOT NULL CHECK (SO_SAO BETWEEN 1 AND 5),
    NOI_DUNG  VARCHAR(500),
    NGAY_DG   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_HIDDEN INTEGER DEFAULT 0,
    PHAN_HOI_CHI_TIET JSON,
    UNIQUE (MAHOSO),
    FOREIGN KEY (MAHOSO) REFERENCES HO_SO_THI_LUC(MAHOSO),
    FOREIGN KEY (MAKH)   REFERENCES KHACH_HANG(MAKH),
    FOREIGN KEY (MANS)   REFERENCES NHAN_SU(MANS)
);

CREATE SEQUENCE SEQ_DANH_GIA START 1 CACHE 20;

CREATE OR REPLACE FUNCTION trg_gen_madg_func()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.MADG IS NULL THEN
        NEW.MADG := 'DG' || LPAD(nextval('SEQ_DANH_GIA')::text, 6, '0');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_GEN_MADG
BEFORE INSERT ON DANH_GIA
FOR EACH ROW EXECUTE FUNCTION trg_gen_madg_func();

CREATE OR REPLACE VIEW V_RATING_BAC_SI AS
SELECT
    ns.MANS,
    ns.HOTEN,
    ns.CHUYENKHOA,
    COUNT(dg.MADG) AS TONG_LUOT_DANH_GIA,
    ROUND(AVG(dg.SO_SAO), 1) AS RATING_TRUNG_BINH
FROM NHAN_SU ns
LEFT JOIN DANH_GIA dg ON ns.MANS = dg.MANS AND dg.IS_HIDDEN = 0
WHERE ns.IS_DELETED = 0
GROUP BY ns.MANS, ns.HOTEN, ns.CHUYENKHOA;

CREATE INDEX IDX_DG_MANS ON DANH_GIA (MANS);
CREATE INDEX IDX_DG_MAKH ON DANH_GIA (MAKH);


-- ============================================================
-- [G3] GÓI DỊCH VỤ KHÁM
-- ============================================================

CREATE TABLE GOI_KHAM (
    MAGOI     VARCHAR(10) PRIMARY KEY,
    TENGOI    VARCHAR(100) NOT NULL,
    MOTA      VARCHAR(500),
    GIA       NUMERIC(15,2) NOT NULL,
    THOILUONG NUMERIC DEFAULT 30,
    IS_ACTIVE INTEGER DEFAULT 1
);

ALTER TABLE LICH_HEN ADD COLUMN MAGOI VARCHAR(10) NULL,
                      ADD COLUMN TRIEU_CHUNG VARCHAR(500) NULL,
                      ADD COLUMN LOAI_LICH VARCHAR(20) DEFAULT 'Online',
                      ADD COLUMN GIO_HEN TIMESTAMP NULL;

ALTER TABLE LICH_HEN ADD CONSTRAINT FK_LH_GOI FOREIGN KEY (MAGOI) REFERENCES GOI_KHAM(MAGOI);

-- Seed dữ liệu gói khám mẫu
INSERT INTO GOI_KHAM (MAGOI, TENGOI, MOTA, GIA, THOILUONG) VALUES
('GOI01', 'Khám tổng quát mắt', 'Kiểm tra thị lực tổng quát, áp nhãn cầu', 150000, 30);
INSERT INTO GOI_KHAM (MAGOI, TENGOI, MOTA, GIA, THOILUONG) VALUES
('GOI02', 'Đo khúc xạ cắt kính', 'Đo độ cận/viễn/loạn, tư vấn thông số kính', 200000, 45);
INSERT INTO GOI_KHAM (MAGOI, TENGOI, MOTA, GIA, THOILUONG) VALUES
('GOI03', 'Khám chuyên sâu', 'Soi đáy mắt, đo OCT, chẩn đoán bệnh lý võng mạc', 450000, 60);
INSERT INTO GOI_KHAM (MAGOI, TENGOI, MOTA, GIA, THOILUONG) VALUES
('GOI04', 'Tư vấn kính áp tròng', 'Tư vấn và thử kính áp tròng phù hợp', 100000, 30);
COMMIT;


-- ============================================================
-- [G5] LỊCH LÀM VIỆC BÁC SĨ
-- ============================================================

CREATE TABLE LICH_LAM_VIEC (
    MALLV        VARCHAR(10) PRIMARY KEY,
    MANS         VARCHAR(10) NOT NULL,
    NGAY_LAM     DATE NOT NULL,
    GIO_BAT_DAU  NUMERIC(4,2) NOT NULL,
    GIO_KET_THUC NUMERIC(4,2) NOT NULL,
    IS_NGHI      INTEGER DEFAULT 0,
    FOREIGN KEY (MANS) REFERENCES NHAN_SU(MANS),
    CHECK (GIO_KET_THUC > GIO_BAT_DAU)
);

CREATE SEQUENCE SEQ_LICH_LAM_VIEC START 1 CACHE 10;

CREATE OR REPLACE FUNCTION trg_gen_mallv_func()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.MALLV IS NULL THEN
        NEW.MALLV := 'LV' || LPAD(nextval('SEQ_LICH_LAM_VIEC')::text, 6, '0');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_GEN_MALLV
BEFORE INSERT ON LICH_LAM_VIEC
FOR EACH ROW EXECUTE FUNCTION trg_gen_mallv_func();

CREATE OR REPLACE VIEW V_SLOT_TRONG AS
SELECT
    llv.MANS,
    ns.HOTEN AS TEN_BAC_SI,
    llv.NGAY_LAM,
    llv.GIO_BAT_DAU,
    llv.GIO_KET_THUC,
    goi.THOILUONG,
    CASE
        WHEN EXISTS (
            SELECT 1 FROM LICH_HEN lh
            WHERE lh.MANS = llv.MANS
              AND lh.GIO_HEN IS NOT NULL
              AND DATE(lh.GIO_HEN) = llv.NGAY_LAM
              AND EXTRACT(HOUR FROM lh.GIO_HEN) + EXTRACT(MINUTE FROM lh.GIO_HEN)/60.0
                  BETWEEN llv.GIO_BAT_DAU AND llv.GIO_KET_THUC - COALESCE(goi.THOILUONG,30)/60.0
              AND lh.TRANGTHAI != 'Đã hủy'
        ) THEN 'Đã đặt'
        ELSE 'Còn trống'
    END AS TRANG_THAI_SLOT
FROM LICH_LAM_VIEC llv
JOIN NHAN_SU ns ON llv.MANS = ns.MANS
LEFT JOIN LICH_HEN lh2 ON llv.MANS = lh2.MANS
LEFT JOIN GOI_KHAM goi ON lh2.MAGOI = goi.MAGOI
WHERE llv.IS_NGHI = 0
  AND llv.NGAY_LAM >= CURRENT_DATE
  AND ns.IS_DELETED = 0;

CREATE INDEX IDX_LLV_MANS ON LICH_LAM_VIEC (MANS);
CREATE INDEX IDX_LLV_NGAY ON LICH_LAM_VIEC (NGAY_LAM);


-- ============================================================
-- [G6] HÀNG CHỜ — QUEUE MANAGEMENT
-- ============================================================

CREATE TABLE HANG_CHO (
    MAHC         VARCHAR(10) PRIMARY KEY,
    MAKH         VARCHAR(10),
    TEN_KHACH    VARCHAR(100),
    SO_THU_TU    NUMERIC NOT NULL,
    LOAI_KHACH   VARCHAR(20) DEFAULT 'Walk-in',
    MALH         VARCHAR(10) NULL,
    MANS_PHAN_CONG VARCHAR(10) NULL,
    TRANG_THAI   VARCHAR(30) DEFAULT 'Đang chờ',
    GIO_DANG_KY  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    GIO_VAO_KHAM TIMESTAMP NULL,
    GHI_CHU      VARCHAR(255),
    FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH),
    FOREIGN KEY (MALH) REFERENCES LICH_HEN(MALH),
    FOREIGN KEY (MANS_PHAN_CONG) REFERENCES NHAN_SU(MANS)
);

CREATE SEQUENCE SEQ_HANG_CHO START 1 CACHE 1;

CREATE OR REPLACE FUNCTION trg_gen_mahc_func()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.MAHC IS NULL THEN
        NEW.MAHC := 'HC' || LPAD(nextval('SEQ_HANG_CHO')::text, 6, '0');
    END IF;
    IF NEW.SO_THU_TU IS NULL THEN
        SELECT COALESCE(MAX(SO_THU_TU), 0) + 1 INTO NEW.SO_THU_TU
        FROM HANG_CHO
        WHERE DATE(GIO_DANG_KY) = CURRENT_DATE;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_GEN_MAHC
BEFORE INSERT ON HANG_CHO
FOR EACH ROW EXECUTE FUNCTION trg_gen_mahc_func();

CREATE OR REPLACE VIEW V_HANG_CHO_HOM_NAY AS
SELECT
    hc.MAHC,
    hc.SO_THU_TU,
    hc.LOAI_KHACH,
    COALESCE(kh.HOTEN, hc.TEN_KHACH) AS TEN_KHACH,
    kh.SDT,
    hc.MANS_PHAN_CONG,
    ns.HOTEN AS TEN_BAC_SI,
    goi.TENGOI AS GOI_KHAM,
    hc.TRANG_THAI,
    hc.GIO_DANG_KY,
    hc.GIO_VAO_KHAM,
    ROUND(EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - hc.GIO_DANG_KY)) / 60) AS PHUT_CHO
FROM HANG_CHO hc
LEFT JOIN KHACH_HANG kh ON hc.MAKH = kh.MAKH
LEFT JOIN NHAN_SU ns ON hc.MANS_PHAN_CONG = ns.MANS
LEFT JOIN LICH_HEN lh ON hc.MALH = lh.MALH
LEFT JOIN GOI_KHAM goi ON lh.MAGOI = goi.MAGOI
WHERE DATE(hc.GIO_DANG_KY) = CURRENT_DATE
  AND hc.TRANG_THAI NOT IN ('Hoàn thành', 'Bỏ về')
ORDER BY
    CASE WHEN hc.LOAI_KHACH = 'Walk-in' THEN 0 ELSE 1 END,
    hc.SO_THU_TU;

CREATE INDEX IDX_HC_NGAY  ON HANG_CHO (GIO_DANG_KY);
CREATE INDEX IDX_HC_TRANG ON HANG_CHO (TRANG_THAI);
CREATE INDEX IDX_HC_LOAI  ON HANG_CHO (LOAI_KHACH);


-- ============================================================
-- [G7] DỊCH VỤ KHÁM & PHÍ DỊCH VỤ
-- ============================================================

CREATE TABLE DICH_VU_KHAM (
    MADV   VARCHAR(10) PRIMARY KEY,
    TENDV  VARCHAR(100) NOT NULL,
    GIA    NUMERIC(15,2) NOT NULL,
    MOTA   VARCHAR(255),
    IS_ACTIVE INTEGER DEFAULT 1
);

CREATE TABLE CT_HOA_DON_DV (
    MAHD    VARCHAR(10),
    MADV    VARCHAR(10),
    SOLUONG NUMERIC DEFAULT 1,
    DONGIA  NUMERIC(15,2),
    PRIMARY KEY (MAHD, MADV),
    FOREIGN KEY (MAHD) REFERENCES HOA_DON(MAHD),
    FOREIGN KEY (MADV) REFERENCES DICH_VU_KHAM(MADV)
);

CREATE OR REPLACE FUNCTION trg_ct_hoa_don_dv_after_func()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE HOA_DON
        SET TONGTIEN = COALESCE(TONGTIEN, 0) + (NEW.SOLUONG * NEW.DONGIA)
        WHERE MAHD = NEW.MAHD;
    ELSIF TG_OP = 'UPDATE' THEN
        UPDATE HOA_DON
        SET TONGTIEN = COALESCE(TONGTIEN, 0)
                      - (OLD.SOLUONG * OLD.DONGIA)
                      + (NEW.SOLUONG * NEW.DONGIA)
        WHERE MAHD = NEW.MAHD;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE HOA_DON
        SET TONGTIEN = COALESCE(TONGTIEN, 0) - (OLD.SOLUONG * OLD.DONGIA)
        WHERE MAHD = OLD.MAHD;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_CT_HOA_DON_DV_AFTER
AFTER INSERT OR UPDATE OR DELETE ON CT_HOA_DON_DV
FOR EACH ROW EXECUTE FUNCTION trg_ct_hoa_don_dv_after_func();

-- Seed dịch vụ mẫu
INSERT INTO DICH_VU_KHAM VALUES ('DV01', 'Phí khám tổng quát', 150000, 'Phí khám cơ bản', 1);
INSERT INTO DICH_VU_KHAM VALUES ('DV02', 'Phí đo khúc xạ', 200000, 'Đo và tư vấn kính', 1);
INSERT INTO DICH_VU_KHAM VALUES ('DV03', 'Phí soi đáy mắt', 250000, 'Chụp ảnh đáy mắt', 1);
INSERT INTO DICH_VU_KHAM VALUES ('DV04', 'Phí tư vấn kính áp tròng', 100000, 'Thử và tư vấn', 1);
COMMIT;

-- Tạo CT_GOI_KHAM sau khi có DICH_VU_KHAM
CREATE TABLE CT_GOI_KHAM (
    MAGOI   VARCHAR(10),
    MADV    VARCHAR(10),
    SOLUONG NUMERIC DEFAULT 1,
    PRIMARY KEY (MAGOI, MADV),
    FOREIGN KEY (MAGOI) REFERENCES GOI_KHAM(MAGOI),
    FOREIGN KEY (MADV) REFERENCES DICH_VU_KHAM(MADV)
);

CREATE INDEX IDX_CTHD_DV_MAHD ON CT_HOA_DON_DV (MAHD);


-- ============================================================
-- [G8] TỒN KHO TỐI THIỂU — CẢNH BÁO THỦ KHO
-- ============================================================

ALTER TABLE SAN_PHAM ADD COLUMN TON_KHO_TOI_THIEU NUMERIC DEFAULT 0,
                      ADD COLUMN DON_VI_TINH_KHO VARCHAR(20) NULL;

CREATE OR REPLACE VIEW V_CANH_BAO_TON_KHO AS
SELECT
    sp.MASP,
    sp.TENSP,
    sp.DONVITINH,
    COALESCE(SUM(lh.SOLUONGTON), 0) AS TONG_TON_HIEN_TAI,
    sp.TON_KHO_TOI_THIEU,
    CASE
        WHEN COALESCE(SUM(lh.SOLUONGTON), 0) = 0 THEN 'Het hang'
        WHEN COALESCE(SUM(lh.SOLUONGTON), 0) <= sp.TON_KHO_TOI_THIEU THEN 'Sap het'
        WHEN COALESCE(SUM(lh.SOLUONGTON), 0) <= sp.TON_KHO_TOI_THIEU * 2 THEN 'Canh bao'
        ELSE 'On dinh'
    END AS MUC_DO
FROM SAN_PHAM sp
LEFT JOIN LO_HANG lh ON sp.MASP = lh.MASP
                    AND lh.NGAYHETHAN > CURRENT_DATE
                    AND lh.SOLUONGTON > 0
GROUP BY sp.MASP, sp.TENSP, sp.DONVITINH, sp.TON_KHO_TOI_THIEU
HAVING COALESCE(SUM(lh.SOLUONGTON), 0) <= sp.TON_KHO_TOI_THIEU * 2
    OR COALESCE(SUM(lh.SOLUONGTON), 0) = 0
ORDER BY MUC_DO, TONG_TON_HIEN_TAI;


-- ============================================================
-- [G9] ĐIỂM TÍCH LŨY — LỊCH SỬ & KHUYẾN MÃI
-- ============================================================

CREATE TABLE LICH_SU_DIEM (
    MALSD     VARCHAR(10) PRIMARY KEY,
    MAKH      VARCHAR(10) NOT NULL,
    LOAI      VARCHAR(20) NOT NULL,
    SO_DIEM   NUMERIC NOT NULL,
    LY_DO     VARCHAR(200),
    MAHD      VARCHAR(10) NULL,
    THOI_GIAN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH),
    FOREIGN KEY (MAHD) REFERENCES HOA_DON(MAHD)
);

CREATE SEQUENCE SEQ_LICH_SU_DIEM START 1 CACHE 50;

CREATE OR REPLACE FUNCTION trg_gen_malsd_func()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.MALSD IS NULL THEN
        NEW.MALSD := 'LS' || LPAD(nextval('SEQ_LICH_SU_DIEM')::text, 6, '0');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_GEN_MALSD
BEFORE INSERT ON LICH_SU_DIEM
FOR EACH ROW EXECUTE FUNCTION trg_gen_malsd_func();

CREATE TABLE KHUYEN_MAI (
    MAKM        VARCHAR(10) PRIMARY KEY,
    TENKM       VARCHAR(100) NOT NULL,
    LOAI        VARCHAR(20) NOT NULL,
    GIA_TRI     NUMERIC(15,2) NOT NULL,
    GIAM_TOI_DA NUMERIC(15,2) NULL,
    MA_CODE     VARCHAR(20) UNIQUE,
    NGAY_BD     DATE NOT NULL,
    NGAY_KT     DATE NOT NULL,
    SO_LUONG    NUMERIC NULL,
    DA_DUNG     NUMERIC DEFAULT 0,
    DIEU_KIEN   NUMERIC(15,2) DEFAULT 0,
    DIEU_KIEN_JSON JSON,
    IS_ACTIVE   INTEGER DEFAULT 1,
    CHECK (NGAY_KT >= NGAY_BD)
);

CREATE TABLE KH_KHUYEN_MAI (
    MAKH    VARCHAR(10),
    MAKM    VARCHAR(10),
    MAHD    VARCHAR(10) NULL,
    NGAY_SD TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MAKH, MAKM),
    FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH),
    FOREIGN KEY (MAKM) REFERENCES KHUYEN_MAI(MAKM),
    FOREIGN KEY (MAHD) REFERENCES HOA_DON(MAHD)
);

CREATE INDEX IDX_LSD_MAKH ON LICH_SU_DIEM (MAKH);
CREATE INDEX IDX_LSD_MAHD ON LICH_SU_DIEM (MAHD);
CREATE INDEX IDX_KM_CODE  ON KHUYEN_MAI (MA_CODE);
CREATE INDEX IDX_KM_NGAY  ON KHUYEN_MAI (NGAY_BD, NGAY_KT);

-- ============================================================
-- END OF V2_Feature_PostgreSQL.sql
-- ============================================================