-- ============================================================
-- PHẦN 0: XÓA BẢNG CŨ (AN TOÀN)
-- ============================================================
DROP TABLE KH_KHUYEN_MAI CASCADE CONSTRAINTS;
DROP TABLE LICH_SU_DIEM CASCADE CONSTRAINTS;
DROP TABLE LICH_SU_GIA CASCADE CONSTRAINTS;
DROP TABLE GIAO_DICH_NCC CASCADE CONSTRAINTS;
DROP TABLE token_blacklist CASCADE CONSTRAINTS;
DROP TABLE DANH_GIA CASCADE CONSTRAINTS;
DROP TABLE AUDIT_HOSO_THILUC CASCADE CONSTRAINTS;
DROP TABLE CT_HOA_DON CASCADE CONSTRAINTS;
DROP TABLE CT_HOA_DON_DV CASCADE CONSTRAINTS;
DROP TABLE THANH_TOAN CASCADE CONSTRAINTS;
DROP TABLE HOA_DON CASCADE CONSTRAINTS;
DROP TABLE XU_LY_KINH CASCADE CONSTRAINTS;
DROP TABLE CT_KE_DON CASCADE CONSTRAINTS;
DROP TABLE PHIEU_KE_DON CASCADE CONSTRAINTS;
DROP TABLE LICH_HEN_TRIEU_CHUNG CASCADE CONSTRAINTS;
DROP TABLE CHI_TIET_THI_LUC CASCADE CONSTRAINTS;
DROP TABLE HO_SO_THI_LUC CASCADE CONSTRAINTS;
DROP TABLE HANG_CHO CASCADE CONSTRAINTS;
DROP TABLE LICH_HEN CASCADE CONSTRAINTS;
DROP TABLE LICH_LAM_VIEC CASCADE CONSTRAINTS;
DROP TABLE CHI_TIET_KY_THUAT CASCADE CONSTRAINTS;
DROP TABLE CT_GOI_KHAM CASCADE CONSTRAINTS;
DROP TABLE GOI_KHAM CASCADE CONSTRAINTS;
DROP TABLE DICH_VU_KHAM CASCADE CONSTRAINTS;
DROP TABLE TRIEU_CHUNG CASCADE CONSTRAINTS;
DROP TABLE LO_HANG CASCADE CONSTRAINTS;
DROP TABLE PHIEU_NHAP CASCADE CONSTRAINTS;
DROP TABLE NHA_CUNG_CAP CASCADE CONSTRAINTS;
DROP TABLE SAN_PHAM CASCADE CONSTRAINTS;
DROP TABLE LOAI_SAN_PHAM CASCADE CONSTRAINTS;
DROP TABLE NHAN_SU CASCADE CONSTRAINTS;
DROP TABLE KHACH_HANG CASCADE CONSTRAINTS;
DROP TABLE TAIKHOAN_NHOM CASCADE CONSTRAINTS;
DROP TABLE NHOM_VAITRO CASCADE CONSTRAINTS;
DROP TABLE VAITRO CASCADE CONSTRAINTS;
DROP TABLE NHOM CASCADE CONSTRAINTS;
DROP TABLE CHUC_VU CASCADE CONSTRAINTS;
DROP TABLE TAI_KHOAN CASCADE CONSTRAINTS;
DROP TABLE KHUYEN_MAI CASCADE CONSTRAINTS;

-- ============================================================
-- PHẦN I: TẠO BẢNG
-- ============================================================
CREATE TABLE NHOM (
    MANHOM   VARCHAR2(10)  PRIMARY KEY,
    TENNHOM  NVARCHAR2(100),
    MOTA     NVARCHAR2(500)
);

CREATE TABLE VAITRO (
    MAVAITRO  VARCHAR2(50)  PRIMARY KEY,
    TENVAITRO NVARCHAR2(100),
    MOTA      NVARCHAR2(500)
);

CREATE TABLE NHOM_VAITRO (
    MANHOM   VARCHAR2(10),
    MAVAITRO VARCHAR2(50),
    CONSTRAINT PK_NHOM_VAITRO PRIMARY KEY (MANHOM, MAVAITRO),
    CONSTRAINT FK_NVT_NHOM    FOREIGN KEY (MANHOM)   REFERENCES NHOM(MANHOM),
    CONSTRAINT FK_NVT_VAITRO  FOREIGN KEY (MAVAITRO) REFERENCES VAITRO(MAVAITRO)
);

CREATE TABLE TAI_KHOAN (
    MATK      VARCHAR2(10)  PRIMARY KEY,
    USERNAME  VARCHAR2(50)  UNIQUE,
    PASSWORD  VARCHAR2(255),
    LOAI_TK   NVARCHAR2(20) DEFAULT N'INTERNAL',
    TRANGTHAI NUMBER(1)     DEFAULT 1
);

CREATE TABLE TAIKHOAN_NHOM (
    MATK   VARCHAR2(10),
    MANHOM VARCHAR2(10),
    CONSTRAINT PK_TKN     PRIMARY KEY (MATK, MANHOM),
    CONSTRAINT FK_TKN_TK  FOREIGN KEY (MATK)   REFERENCES TAI_KHOAN(MATK),
    CONSTRAINT FK_TKN_NHM FOREIGN KEY (MANHOM) REFERENCES NHOM(MANHOM)
);

CREATE TABLE CHUC_VU (
    MACV  VARCHAR2(10)  PRIMARY KEY,
    TENCV NVARCHAR2(100)
);

CREATE TABLE NHAN_SU (
    MANS       VARCHAR2(10)  PRIMARY KEY,
    MATK       VARCHAR2(10)  UNIQUE,
    MACV       VARCHAR2(10),
    CCCD       VARCHAR2(12),
    HOTEN      NVARCHAR2(100),
    NGAYSINH   DATE,
    GIOITINH   NVARCHAR2(10),
    SDT        VARCHAR2(15),
    DIACHI     NVARCHAR2(255),
    CHUYENKHOA NVARCHAR2(100),
    IS_DELETED NUMBER(1) DEFAULT 0,
    CONSTRAINT FK_NS_TK FOREIGN KEY (MATK) REFERENCES TAI_KHOAN(MATK),
    CONSTRAINT FK_NS_CV FOREIGN KEY (MACV) REFERENCES CHUC_VU(MACV)
);

CREATE TABLE CHI_TIET_KY_THUAT (
    MANS                VARCHAR2(10)  PRIMARY KEY,
    CHUYEN_NGANH        NVARCHAR2(100),
    CHUNG_CHI_HANH_NGHE NVARCHAR2(100),
    NAM_CAP_CHUNG_CHI   NUMBER(4),
    NOI_CAP             NVARCHAR2(200),
    KINH_NGHIEM_NAM     NUMBER(2)    DEFAULT 0,
    GHI_CHU             NVARCHAR2(500),
    CONSTRAINT FK_CTKT_NS FOREIGN KEY (MANS) REFERENCES NHAN_SU(MANS)
);

CREATE TABLE LICH_LAM_VIEC (
    MALLV        VARCHAR2(10) PRIMARY KEY,
    MANS         VARCHAR2(10) NOT NULL,
    NGAY_LAM     DATE         NOT NULL,
    GIO_BAT_DAU  NUMBER(4,2)  NOT NULL,
    GIO_KET_THUC NUMBER(4,2)  NOT NULL,
    IS_NGHI      NUMBER(1)    DEFAULT 0,
    CONSTRAINT FK_LLV_NS  FOREIGN KEY (MANS) REFERENCES NHAN_SU(MANS),
    CONSTRAINT CK_LLV_GIO CHECK (GIO_BAT_DAU < GIO_KET_THUC)
);

CREATE TABLE KHACH_HANG (
    MAKH        VARCHAR2(10) PRIMARY KEY,
    MATK        VARCHAR2(10) UNIQUE,
    CCCD        VARCHAR2(12),
    HOTEN       NVARCHAR2(100),
    NGAYSINH    DATE,
    GIOITINH    NVARCHAR2(10),
    SDT         VARCHAR2(15) UNIQUE,
    DIACHI      NVARCHAR2(255),
    DIEMTICHLUY NUMBER       DEFAULT 0,
    IS_DELETED  NUMBER(1)    DEFAULT 0,
    CONSTRAINT FK_KH_TK FOREIGN KEY (MATK) REFERENCES TAI_KHOAN(MATK)
);

CREATE TABLE GOI_KHAM (
    MAGOI     VARCHAR2(10)   PRIMARY KEY,
    TENGOI    NVARCHAR2(100) NOT NULL,
    MOTA      NVARCHAR2(500),
    GIA       NUMBER(15,2)  NOT NULL,
    THOILUONG NUMBER        DEFAULT 30,
    IS_ACTIVE NUMBER(1)     DEFAULT 1
);

CREATE TABLE LICH_HEN (
    MALH      VARCHAR2(10) PRIMARY KEY,
    MAKH      VARCHAR2(10),
    MANS      VARCHAR2(10),
    MAGOI     VARCHAR2(10),
    NGAYHEN   TIMESTAMP,
    GIO_HEN   TIMESTAMP,
    LOAI_LICH NVARCHAR2(20) DEFAULT N'Online',
    TRANGTHAI NVARCHAR2(50),
    CONSTRAINT FK_LH_KH  FOREIGN KEY (MAKH)  REFERENCES KHACH_HANG(MAKH),
    CONSTRAINT FK_LH_NS  FOREIGN KEY (MANS)  REFERENCES NHAN_SU(MANS),
    CONSTRAINT FK_LH_GOI FOREIGN KEY (MAGOI) REFERENCES GOI_KHAM(MAGOI)
);

CREATE TABLE HANG_CHO (
    MAHC           VARCHAR2(10)  PRIMARY KEY,
    MAKH           VARCHAR2(10),
    TEN_KHACH      NVARCHAR2(100),
    SO_THU_TU      NUMBER        NOT NULL,
    LOAI_KHACH     NVARCHAR2(20) DEFAULT N'Walk-in',
    MALH           VARCHAR2(10),
    MANS_PHAN_CONG VARCHAR2(10),
    TRANG_THAI     NVARCHAR2(30) DEFAULT N'Đang chờ',
    GIO_DANG_KY    TIMESTAMP     DEFAULT SYSTIMESTAMP,
    GIO_VAO_KHAM   TIMESTAMP,
    GHI_CHU        NVARCHAR2(255),
    CONSTRAINT FK_HC_KH FOREIGN KEY (MAKH)           REFERENCES KHACH_HANG(MAKH),
    CONSTRAINT FK_HC_LH FOREIGN KEY (MALH)           REFERENCES LICH_HEN(MALH),
    CONSTRAINT FK_HC_NS FOREIGN KEY (MANS_PHAN_CONG) REFERENCES NHAN_SU(MANS)
);

CREATE TABLE TRIEU_CHUNG (
    MA_TC     VARCHAR2(10)   PRIMARY KEY,
    TEN_TC    NVARCHAR2(200) NOT NULL,
    MO_TA     NVARCHAR2(500),
    IS_ACTIVE NUMBER(1)     DEFAULT 1
);

CREATE TABLE LICH_HEN_TRIEU_CHUNG (
    MALH        VARCHAR2(10),
    MA_TC       VARCHAR2(10),
    MO_TA_TU_DO NVARCHAR2(500),
    CONSTRAINT PK_LH_TC    PRIMARY KEY (MALH, MA_TC),
    CONSTRAINT FK_LH_TC_LH FOREIGN KEY (MALH)  REFERENCES LICH_HEN(MALH),
    CONSTRAINT FK_LH_TC_TC FOREIGN KEY (MA_TC) REFERENCES TRIEU_CHUNG(MA_TC)
);

CREATE TABLE HO_SO_THI_LUC (
    MAHOSO   VARCHAR2(10)   PRIMARY KEY,
    MAKH     VARCHAR2(10),
    MANS     VARCHAR2(10),
    NGAYKHAM TIMESTAMP,
    KETLUAN  NVARCHAR2(255),
    CONSTRAINT FK_HS_KH FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH),
    CONSTRAINT FK_HS_NS FOREIGN KEY (MANS) REFERENCES NHAN_SU(MANS)
);

CREATE TABLE CHI_TIET_THI_LUC (
    MAHOSO        VARCHAR2(10),
    MAT           CHAR(1),
    DOCAU_SPH     NUMBER(4,2),
    DOTRU_CYL     NUMBER(4,2),
    TRUC_AX       NUMBER(3),
    KHOANGCACH_PD NUMBER(3,1),
    DOCONG_ADD    NUMBER(4,2),
    CONSTRAINT PK_CTTTL    PRIMARY KEY (MAHOSO, MAT),
    CONSTRAINT FK_CTTTL_HS FOREIGN KEY (MAHOSO) REFERENCES HO_SO_THI_LUC(MAHOSO)
);

CREATE TABLE AUDIT_HOSO_THILUC (
    MAAUDIT         VARCHAR2(20) PRIMARY KEY,
    MAHOSO          VARCHAR2(10),
    OLD_KETLUAN     NVARCHAR2(255),
    NEW_KETLUAN     NVARCHAR2(255),
    THOI_GIAN       TIMESTAMP    DEFAULT SYSTIMESTAMP,
    NGUOI_THUC_HIEN VARCHAR2(50)
);

CREATE TABLE DANH_GIA (
    MADG              VARCHAR2(10) PRIMARY KEY,
    MAHOSO            VARCHAR2(10) NOT NULL,
    MAKH              VARCHAR2(10) NOT NULL,
    MANS              VARCHAR2(10) NOT NULL,
    SO_SAO            NUMBER(1)    NOT NULL,
    NOI_DUNG          NVARCHAR2(500),
    PHAN_HOI_CHI_TIET JSON,
    NGAY_DG           TIMESTAMP    DEFAULT SYSTIMESTAMP,
    IS_HIDDEN         NUMBER(1)    DEFAULT 0,
    CONSTRAINT UK_DG_MAHOSO UNIQUE (MAHOSO),
    CONSTRAINT CK_DG_SAO    CHECK (SO_SAO BETWEEN 1 AND 5),
    CONSTRAINT FK_DG_HS     FOREIGN KEY (MAHOSO) REFERENCES HO_SO_THI_LUC(MAHOSO),
    CONSTRAINT FK_DG_KH     FOREIGN KEY (MAKH)   REFERENCES KHACH_HANG(MAKH),
    CONSTRAINT FK_DG_NS     FOREIGN KEY (MANS)   REFERENCES NHAN_SU(MANS)
);

CREATE TABLE LOAI_SAN_PHAM (
    MALOAI  VARCHAR2(10)   PRIMARY KEY,
    TENLOAI NVARCHAR2(100)
);

CREATE TABLE SAN_PHAM (
    MASP              VARCHAR2(10)  PRIMARY KEY,
    MALOAI            VARCHAR2(10),
    TENSP             NVARCHAR2(100),
    DONVITINH         NVARCHAR2(20),
    LATHUOC           NUMBER(1),
    GIABAN            NUMBER(15,2),
    TON_KHO_TOI_THIEU NUMBER       DEFAULT 0,
    DON_VI_TINH_KHO   NVARCHAR2(20),
    CONSTRAINT FK_SP_LOAI FOREIGN KEY (MALOAI) REFERENCES LOAI_SAN_PHAM(MALOAI)
);

CREATE TABLE PHIEU_KE_DON (
    MADON     VARCHAR2(20)   PRIMARY KEY,
    MAHOSO    VARCHAR2(10),
    MANS      VARCHAR2(10),
    NGAYKEDON DATE,
    LOIDAN    NVARCHAR2(255),
    CONSTRAINT FK_PKD_HS FOREIGN KEY (MAHOSO) REFERENCES HO_SO_THI_LUC(MAHOSO),
    CONSTRAINT FK_PKD_NS FOREIGN KEY (MANS)   REFERENCES NHAN_SU(MANS)
);

CREATE TABLE CT_KE_DON (
    MADON    VARCHAR2(20),
    MASP     VARCHAR2(10),
    SOLUONG  NUMBER,
    LIEUDUNG NVARCHAR2(100),
    CACHDUNG NVARCHAR2(100),
    CONSTRAINT PK_CTKD     PRIMARY KEY (MADON, MASP),
    CONSTRAINT FK_CTKD_PKD FOREIGN KEY (MADON) REFERENCES PHIEU_KE_DON(MADON),
    CONSTRAINT FK_CTKD_SP  FOREIGN KEY (MASP)  REFERENCES SAN_PHAM(MASP)
);

CREATE TABLE XU_LY_KINH (
    MAXL            VARCHAR2(10)   PRIMARY KEY,
    MADON           VARCHAR2(20)   NOT NULL,
    THONG_SO_KINH   JSON,
    TRANG_THAI      NVARCHAR2(30)  DEFAULT N'Chờ xử lý',
    NGAY_BAT_DAU    TIMESTAMP,
    NGAY_HOAN_THANH TIMESTAMP,
    MANS_KY_THUAT   VARCHAR2(10),
    GHI_CHU         NVARCHAR2(255),
    CONSTRAINT FK_XLK_PKD FOREIGN KEY (MADON)         REFERENCES PHIEU_KE_DON(MADON),
    CONSTRAINT FK_XLK_NS  FOREIGN KEY (MANS_KY_THUAT) REFERENCES NHAN_SU(MANS)
);

CREATE TABLE NHA_CUNG_CAP (
    MANCC  VARCHAR2(10)   PRIMARY KEY,
    TENNCC NVARCHAR2(100),
    SDT    VARCHAR2(15),
    DIACHI NVARCHAR2(255)
);

CREATE TABLE PHIEU_NHAP (
    MAPN     VARCHAR2(10)  PRIMARY KEY,
    MANCC    VARCHAR2(10),
    MANS     VARCHAR2(10),
    NGAYNHAP TIMESTAMP,
    TONGTIEN NUMBER(15,2)  DEFAULT 0,
    CONSTRAINT FK_PN_NCC FOREIGN KEY (MANCC) REFERENCES NHA_CUNG_CAP(MANCC),
    CONSTRAINT FK_PN_NS  FOREIGN KEY (MANS)  REFERENCES NHAN_SU(MANS)
);

CREATE TABLE GIAO_DICH_NCC (
    MAGD    VARCHAR2(10)  PRIMARY KEY,
    MANCC   VARCHAR2(10)  NOT NULL,
    LOAI    NVARCHAR2(20) NOT NULL,
    SO_TIEN NUMBER(15,2)  NOT NULL,
    NGAY_GD TIMESTAMP     DEFAULT SYSTIMESTAMP,
    MAPN    VARCHAR2(10),
    GHI_CHU NVARCHAR2(255),
    CONSTRAINT FK_GD_NCC FOREIGN KEY (MANCC) REFERENCES NHA_CUNG_CAP(MANCC),
    CONSTRAINT FK_GD_PN  FOREIGN KEY (MAPN)  REFERENCES PHIEU_NHAP(MAPN)
);

CREATE TABLE LO_HANG (
    MALO        VARCHAR2(10)  PRIMARY KEY,
    MASP        VARCHAR2(10),
    MAPN        VARCHAR2(10),
    NGAYSANXUAT DATE,
    NGAYHETHAN  DATE,
    SOLUONGNHAP NUMBER,
    SOLUONGTON  NUMBER,
    GIANHAP     NUMBER(15,2),
    CONSTRAINT FK_LO_SP FOREIGN KEY (MASP) REFERENCES SAN_PHAM(MASP),
    CONSTRAINT FK_LO_PN FOREIGN KEY (MAPN) REFERENCES PHIEU_NHAP(MAPN)
);

CREATE TABLE DICH_VU_KHAM (
    MADV      VARCHAR2(10)   PRIMARY KEY,
    TENDV     NVARCHAR2(100) NOT NULL,
    GIA       NUMBER(15,2)   NOT NULL,
    MOTA      NVARCHAR2(255),
    IS_ACTIVE NUMBER(1)     DEFAULT 1
);

CREATE TABLE CT_GOI_KHAM (
    MAGOI   VARCHAR2(10),
    MADV    VARCHAR2(10),
    SOLUONG NUMBER DEFAULT 1,
    CONSTRAINT PK_CT_GOI     PRIMARY KEY (MAGOI, MADV),
    CONSTRAINT FK_CT_GOI_GOI FOREIGN KEY (MAGOI) REFERENCES GOI_KHAM(MAGOI),
    CONSTRAINT FK_CT_GOI_DV  FOREIGN KEY (MADV)  REFERENCES DICH_VU_KHAM(MADV)
);

CREATE TABLE HOA_DON (
    MAHD      VARCHAR2(10)   PRIMARY KEY,
    MAKH      VARCHAR2(10),
    MANS      VARCHAR2(10),
    MAHOSO    VARCHAR2(10),
    MADON     VARCHAR2(20),
    NGAYLAP   TIMESTAMP,
    TONGTIEN  NUMBER(15,2)   DEFAULT 0,
    TRANGTHAI NVARCHAR2(50)  DEFAULT N'Chưa thanh toán',
    IS_DELETED NUMBER(1)     DEFAULT 0,
    CONSTRAINT FK_HD_KH  FOREIGN KEY (MAKH)   REFERENCES KHACH_HANG(MAKH),
    CONSTRAINT FK_HD_NS  FOREIGN KEY (MANS)   REFERENCES NHAN_SU(MANS),
    CONSTRAINT FK_HD_HS  FOREIGN KEY (MAHOSO) REFERENCES HO_SO_THI_LUC(MAHOSO),
    CONSTRAINT FK_HD_PKD FOREIGN KEY (MADON)  REFERENCES PHIEU_KE_DON(MADON)
);

CREATE TABLE CT_HOA_DON (
    MAHD    VARCHAR2(10),
    MALO    VARCHAR2(10),
    MASP    VARCHAR2(10),
    SOLUONG NUMBER,
    DONGIA  NUMBER(15,2),
    CONSTRAINT PK_CTHD    PRIMARY KEY (MAHD, MALO),
    CONSTRAINT FK_CTHD_HD FOREIGN KEY (MAHD) REFERENCES HOA_DON(MAHD),
    CONSTRAINT FK_CTHD_LO FOREIGN KEY (MALO) REFERENCES LO_HANG(MALO),
    CONSTRAINT FK_CTHD_SP FOREIGN KEY (MASP) REFERENCES SAN_PHAM(MASP)
);

CREATE TABLE CT_HOA_DON_DV (
    MAHD    VARCHAR2(10),
    MADV    VARCHAR2(10),
    SOLUONG NUMBER       DEFAULT 1,
    DONGIA  NUMBER(15,2),
    CONSTRAINT PK_CTHD_DV    PRIMARY KEY (MAHD, MADV),
    CONSTRAINT FK_CTHD_DV_HD FOREIGN KEY (MAHD) REFERENCES HOA_DON(MAHD),
    CONSTRAINT FK_CTHD_DV_DV FOREIGN KEY (MADV) REFERENCES DICH_VU_KHAM(MADV)
);

CREATE TABLE THANH_TOAN (
    MATT          VARCHAR2(10)  PRIMARY KEY,
    MAHD          VARCHAR2(10)  NOT NULL,
    MANS          VARCHAR2(10)  NOT NULL,
    NGAYTHANHTOAN TIMESTAMP     DEFAULT SYSTIMESTAMP,
    SOTIEN        NUMBER(15,2)  NOT NULL,
    PHUONGTHUC    NVARCHAR2(50),
    TRANGTHAI     NVARCHAR2(50) DEFAULT N'Hoàn thành',
    GHICHU        NVARCHAR2(255),
    CONSTRAINT FK_TT_HD  FOREIGN KEY (MAHD) REFERENCES HOA_DON(MAHD),
    CONSTRAINT FK_TT_NS  FOREIGN KEY (MANS) REFERENCES NHAN_SU(MANS),
    CONSTRAINT CHK_TT_SOTIEN CHECK (SOTIEN >= 0)
);

CREATE TABLE LICH_SU_DIEM (
    MALSD     VARCHAR2(10)  PRIMARY KEY,
    MAKH      VARCHAR2(10)  NOT NULL,
    LOAI      NVARCHAR2(20) NOT NULL,
    SO_DIEM   NUMBER        NOT NULL,
    LY_DO     NVARCHAR2(200),
    MAHD      VARCHAR2(10),
    THOI_GIAN TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_LSD_KH  FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH),
    CONSTRAINT FK_LSD_HD  FOREIGN KEY (MAHD) REFERENCES HOA_DON(MAHD),
    CONSTRAINT CK_LSD_LOAI CHECK (LOAI IN (N'Cong', N'Tru', N'Quy_doi', N'Hoan'))
);

CREATE TABLE LICH_SU_GIA (
    MALSG          VARCHAR2(10)  PRIMARY KEY,
    MASP           VARCHAR2(10)  NOT NULL,
    GIA_CU         NUMBER(15,2)  NOT NULL,
    GIA_MOI        NUMBER(15,2)  NOT NULL,
    NGAY_AP_DUNG   TIMESTAMP     DEFAULT SYSTIMESTAMP,
    NGUOI_CAP_NHAT VARCHAR2(50),
    LY_DO          NVARCHAR2(200),
    CONSTRAINT FK_LSG_SP FOREIGN KEY (MASP) REFERENCES SAN_PHAM(MASP)
);

CREATE TABLE KHUYEN_MAI (
    MAKM        VARCHAR2(10)   PRIMARY KEY,
    TENKM       NVARCHAR2(100) NOT NULL,
    LOAI        NVARCHAR2(20)  NOT NULL,
    GIA_TRI     NUMBER(15,2)   NOT NULL,
    GIAM_TOI_DA NUMBER(15,2),
    MA_CODE     VARCHAR2(20)   UNIQUE,
    NGAY_BD     DATE           NOT NULL,
    NGAY_KT     DATE           NOT NULL,
    SO_LUONG    NUMBER,
    DA_DUNG     NUMBER         DEFAULT 0,
    DIEU_KIEN   NUMBER(15,2)   DEFAULT 0,
    IS_ACTIVE   NUMBER(1)      DEFAULT 1,
    CONSTRAINT CK_KM_NGAY CHECK (NGAY_KT >= NGAY_BD)
);

CREATE TABLE KH_KHUYEN_MAI (
    MAKH    VARCHAR2(10),
    MAKM    VARCHAR2(10),
    MAHD    VARCHAR2(10),
    NGAY_SD TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_KH_KM   PRIMARY KEY (MAKH, MAKM),
    CONSTRAINT FK_KHKM_KH FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH),
    CONSTRAINT FK_KHKM_KM FOREIGN KEY (MAKM) REFERENCES KHUYEN_MAI(MAKM),
    CONSTRAINT FK_KHKM_HD FOREIGN KEY (MAHD) REFERENCES HOA_DON(MAHD)
);

CREATE TABLE token_blacklist (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR2(512) NOT NULL,
    expiry_date TIMESTAMP NOT NULL
);


COMMIT;