

-- ============================================================
-- 7. INDEXES
-- ============================================================

CREATE INDEX IDX_KH_SDT          ON KHACH_HANG(SDT);
CREATE UNIQUE INDEX IDX_NS_MATK  ON NHAN_SU(MATK);
CREATE INDEX IDX_CTHD_MAHD       ON CT_HOA_DON(MAHD);
CREATE INDEX IDX_HS_MAKH         ON HO_SO_THI_LUC(MAKH);
CREATE INDEX IDX_LO_TON_HSD      ON LO_HANG(SOLUONGTON, NGAYHETHAN);
CREATE INDEX IDX_TT_THONGKE      ON THANH_TOAN(TRANGTHAI, NGAYTHANHTOAN);
CREATE INDEX IDX_HD_MAKH_NGAY    ON HOA_DON(MAKH, NGAYLAP);
CREATE INDEX IDX_HD_MAKH_TRANG   ON HOA_DON(MAKH, TRANGTHAI);
CREATE INDEX IDX_LLV_MANS_NGAY   ON LICH_LAM_VIEC(MANS, NGAY_LAM, IS_NGHI);
CREATE INDEX IDX_LH_MANS_NGAY    ON LICH_HEN(MANS, NGAYHEN, TRANGTHAI);
CREATE INDEX IDX_LH_NGAY_TRANG   ON LICH_HEN(NGAYHEN, TRANGTHAI);
CREATE INDEX IDX_HC_GIO_TRANG    ON HANG_CHO(GIO_DANG_KY, TRANG_THAI);
CREATE INDEX IDX_LH_TC_MA_TC     ON LICH_HEN_TRIEU_CHUNG(MA_TC);
CREATE INDEX IDX_TT_MAHD         ON THANH_TOAN(MAHD);
CREATE INDEX IDX_TT_MANS         ON THANH_TOAN(MANS);
CREATE INDEX IDX_LSD_MAKH        ON LICH_SU_DIEM(MAKH);
CREATE INDEX IDX_LSD_MAHD        ON LICH_SU_DIEM(MAHD);
CREATE INDEX idx_token ON token_blacklist(token);
CREATE UNIQUE INDEX IDX_TRUNG_LICH_HEN ON LICH_HEN (
    CASE WHEN TRANGTHAI != N'Đã hủy' THEN MANS END,
    CASE WHEN TRANGTHAI != N'Đã hủy' THEN GIO_HEN END
);