CREATE OR REPLACE VIEW V_DOANH_THU_THANG AS 
SELECT 
    TO_CHAR(tt.NGAYTHANHTOAN, 'YYYY-MM') AS THANG, 
    COUNT(DISTINCT hd.MAHD) AS SO_HOA_DON, 
    SUM(tt.SOTIEN) AS TONG_DOANH_THU 
FROM THANH_TOAN tt 
JOIN HOA_DON hd ON tt.MAHD = hd.MAHD 
WHERE tt.TRANGTHAI = N'HOAN_THANH' 
GROUP BY TO_CHAR(tt.NGAYTHANHTOAN, 'YYYY-MM');
