-- ============================================================
-- 4. VIEWS
-- ============================================================

CREATE OR REPLACE VIEW V_RATING_BAC_SI AS
SELECT ns.MANS, ns.HOTEN, ns.CHUYENKHOA,
       COUNT(dg.MADG)          AS TONG_LUOT_DANH_GIA,
       ROUND(AVG(dg.SO_SAO),1) AS RATING_TRUNG_BINH
FROM   NHAN_SU ns
LEFT JOIN DANH_GIA dg ON ns.MANS = dg.MANS AND dg.IS_HIDDEN = 0
WHERE  ns.IS_DELETED = 0
GROUP BY ns.MANS, ns.HOTEN, ns.CHUYENKHOA;

CREATE OR REPLACE VIEW V_SLOT_TRONG AS
SELECT llv.MANS, ns.HOTEN AS TEN_BAC_SI, llv.NGAY_LAM, llv.GIO_BAT_DAU, llv.GIO_KET_THUC,
       CASE WHEN EXISTS (
           SELECT 1 FROM LICH_HEN lh
           WHERE lh.MANS = llv.MANS AND lh.GIO_HEN IS NOT NULL
             AND TRUNC(lh.GIO_HEN) = llv.NGAY_LAM
             AND lh.TRANGTHAI != N'Đã hủy'
             AND EXTRACT(HOUR FROM lh.GIO_HEN) + EXTRACT(MINUTE FROM lh.GIO_HEN) / 60.0
                 BETWEEN llv.GIO_BAT_DAU AND llv.GIO_KET_THUC
       ) THEN N'Đã đặt' ELSE N'Còn trống' END AS TRANG_THAI_SLOT
FROM   LICH_LAM_VIEC llv
JOIN   NHAN_SU ns ON llv.MANS = ns.MANS
WHERE  llv.IS_NGHI = 0 AND llv.NGAY_LAM >= TRUNC(SYSDATE) AND ns.IS_DELETED = 0;

CREATE OR REPLACE VIEW V_HANG_CHO_HOM_NAY AS
SELECT hc.MAHC, hc.SO_THU_TU, hc.LOAI_KHACH,
       NVL(kh.HOTEN, hc.TEN_KHACH) AS TEN_KHACH, kh.SDT,
       ns.HOTEN AS TEN_BAC_SI, gk.TENGOI AS GOI_KHAM,
       hc.TRANG_THAI, hc.GIO_DANG_KY, hc.GIO_VAO_KHAM,
       ROUND((EXTRACT(DAY FROM (SYSTIMESTAMP - hc.GIO_DANG_KY)) * 1440 +
              EXTRACT(HOUR FROM (SYSTIMESTAMP - hc.GIO_DANG_KY)) * 60 +
              EXTRACT(MINUTE FROM (SYSTIMESTAMP - hc.GIO_DANG_KY)) +
              EXTRACT(SECOND FROM (SYSTIMESTAMP - hc.GIO_DANG_KY)) / 60)) AS PHUT_CHO
FROM   HANG_CHO hc
LEFT JOIN KHACH_HANG kh ON hc.MAKH = kh.MAKH
LEFT JOIN NHAN_SU    ns ON hc.MANS_PHAN_CONG = ns.MANS
LEFT JOIN LICH_HEN   lh ON hc.MALH = lh.MALH
LEFT JOIN GOI_KHAM   gk ON lh.MAGOI = gk.MAGOI
WHERE  TRUNC(hc.GIO_DANG_KY) = TRUNC(SYSDATE)
  AND  hc.TRANG_THAI NOT IN (N'Hoàn thành', N'Bỏ về')
ORDER BY CASE WHEN hc.LOAI_KHACH = N'Walk-in' THEN 0 ELSE 1 END, hc.SO_THU_TU;

CREATE OR REPLACE VIEW V_CANH_BAO_TON_KHO AS
SELECT sp.MASP, sp.TENSP, sp.DONVITINH,
       NVL(SUM(lh.SOLUONGTON), 0) AS TONG_TON,
       sp.TON_KHO_TOI_THIEU,
       CASE WHEN NVL(SUM(lh.SOLUONGTON), 0) = 0                         THEN N'Het hang'
            WHEN NVL(SUM(lh.SOLUONGTON), 0) <= sp.TON_KHO_TOI_THIEU      THEN N'Sap het'
            WHEN NVL(SUM(lh.SOLUONGTON), 0) <= sp.TON_KHO_TOI_THIEU * 2  THEN N'Canh bao'
            ELSE N'On dinh' END AS MUC_DO
FROM   SAN_PHAM sp
LEFT JOIN LO_HANG lh ON sp.MASP = lh.MASP AND lh.NGAYHETHAN > SYSDATE AND lh.SOLUONGTON > 0
GROUP BY sp.MASP, sp.TENSP, sp.DONVITINH, sp.TON_KHO_TOI_THIEU
HAVING NVL(SUM(lh.SOLUONGTON), 0) <= sp.TON_KHO_TOI_THIEU * 2
    OR NVL(SUM(lh.SOLUONGTON), 0) = 0;

CREATE OR REPLACE VIEW V_LICH_HEN_TRIEU_CHUNG AS
SELECT lh.MALH, lh.NGAYHEN, lh.MAKH,
       kh.HOTEN AS TEN_KHACH, lh.TRANGTHAI,
       tc.MA_TC, tc.TEN_TC, lhtc.MO_TA_TU_DO
FROM   LICH_HEN lh
JOIN   LICH_HEN_TRIEU_CHUNG lhtc ON lh.MALH  = lhtc.MALH
JOIN   TRIEU_CHUNG          tc   ON lhtc.MA_TC = tc.MA_TC
LEFT JOIN KHACH_HANG        kh   ON lh.MAKH   = kh.MAKH;

